// Data awal (seed) stok mobil Dealer Pak Aji — jual beli mobil bekas.
// Harga adalah estimasi dan bisa diubah dari halaman Admin.
const SEED_VERSION = 2;

const DEFAULT_SETTINGS = {
  dealerName: 'Dealer Pak Aji',
  tagline: 'Jual beli mobil bekas berkualitas. Unit terinspeksi, surat lengkap, kredit mudah.',
  whatsapp: '6281234567890',
  phone: '0812-3456-7890',
  email: 'info@dealerpakaji.id',
  address: 'Jl. Raya Utama No. 88, Jakarta Timur',
  hours: 'Senin–Jumat: 08.00–17.00; Sabtu: 08.00–16.00; Minggu: 09.00–14.00',
  instagram: '',
  facebook: '',
  adminPin: '1234',
};

const SEED_CARS = [
  {
    id: 'raize-gr-2022',
    brand: 'Toyota', model: 'Raize', variant: '1.0T GR Sport CVT',
    year: 2022, type: 'SUV', condition: 'Bekas', status: 'Tersedia',
    price: 235000000, transmission: 'CVT', fuel: 'Bensin',
    engine: '998 cc Turbo, 98 PS', seats: 5, km: 35000, color: 'Abu-abu Two Tone',
    image: 'assets/cars/toyota-raize.webp', featured: true,
    features: ['Servis resmi Toyota', 'Pajak hidup', 'Tangan pertama', 'Toyota Safety Sense', 'Velg 17" GR Sport'],
    description: 'Compact SUV turbo yang irit dan lincah, kondisi istimewa seperti baru. Riwayat servis lengkap di bengkel resmi.',
  },
  {
    id: 'chery-c5-2025',
    brand: 'Chery', model: 'C5', variant: '1.5T Z CVT',
    year: 2025, type: 'SUV', condition: 'Bekas', status: 'Tersedia',
    price: 289000000, transmission: 'CVT', fuel: 'Bensin',
    engine: '1.498 cc Turbo, 147 PS', seats: 5, km: 9000, color: 'Hitam',
    image: 'assets/cars/chery-c5.webp', featured: true,
    features: ['Garansi pabrik masih berlaku', 'Panoramic sunroof', 'ADAS lengkap', 'Layar ganda 10,25"', 'Wireless charger'],
    description: 'Crossover futuristis kilometer rendah, garansi pabrik masih aktif. Fitur melimpah dengan harga jauh di bawah baru.',
  },
  {
    id: 'creta-nline-2024',
    brand: 'Hyundai', model: 'Creta', variant: 'N Line 1.5 Turbo DCT',
    year: 2024, type: 'SUV', condition: 'Bekas', status: 'Tersedia',
    price: 405000000, transmission: 'DCT', fuel: 'Bensin',
    engine: '1.482 cc Turbo, 160 PS', seats: 5, km: 12000, color: 'Titan Grey',
    image: 'assets/cars/hyundai-creta.webp', featured: true,
    features: ['Hyundai SmartSense', 'Bose sound system', 'Panoramic sunroof', 'Paddle shift', 'Bodykit N Line'],
    description: 'SUV sporty N Line dengan performa turbo dan fitur keselamatan kelas atas. Pemakaian pribadi, sangat terawat.',
  },
  {
    id: 'xpander-cross-2024',
    brand: 'Mitsubishi', model: 'Xpander Cross', variant: 'Premium CVT',
    year: 2024, type: 'MPV', condition: 'Bekas', status: 'Tersedia',
    price: 315000000, transmission: 'CVT', fuel: 'Bensin',
    engine: '1.499 cc, 105 PS', seats: 7, km: 14000, color: 'Jet Black Mica',
    image: 'assets/cars/mitsubishi-xpander-cross.webp', featured: true,
    features: ['Ground clearance 225 mm', 'Electric parking brake', 'Auto hold', 'Layar 9"', 'Servis resmi'],
    description: 'Crossover MPV 7 penumpang yang tangguh untuk keluarga. Kondisi mulus, interior bersih dan wangi.',
  },
  {
    id: 'xl7-hybrid-2024',
    brand: 'Suzuki', model: 'XL7', variant: 'Alpha Hybrid AT',
    year: 2024, type: 'MPV', condition: 'Bekas', status: 'Tersedia',
    price: 248000000, transmission: 'AT', fuel: 'Hybrid',
    engine: '1.462 cc Mild Hybrid, 105 PS', seats: 7, km: 15000, color: 'Champagne Two Tone',
    image: 'assets/cars/suzuki-xl7.png', featured: true,
    features: ['Smart Hybrid Vehicle by Suzuki', 'Kamera 360°', 'Cruise control', 'Pajak panjang', 'Tangan pertama'],
    description: 'SUV 7 seater irit berkat teknologi hybrid. Tampilan gagah, kilometer rendah, siap pakai.',
  },
  {
    id: 'alphard-hev-2024',
    brand: 'Toyota', model: 'Alphard', variant: '2.5 HEV',
    year: 2024, type: 'MPV', condition: 'Bekas', status: 'Booking',
    price: 1450000000, transmission: 'e-CVT', fuel: 'Hybrid',
    engine: '2.487 cc Hybrid, 250 PS', seats: 7, km: 9000, color: 'Platinum White Pearl',
    image: 'assets/cars/toyota-alphard.jpg', featured: true,
    features: ['Executive lounge seat', 'Sunroof ganda', 'JBL premium audio', 'Toyota Safety Sense', 'Garansi pabrik'],
    description: 'MPV premium kelas eksekutif, kilometer sangat rendah dan kondisi seperti baru.',
  },
  {
    id: 'innova-v-2021',
    brand: 'Toyota', model: 'Kijang Innova', variant: '2.4 V Diesel AT',
    year: 2021, type: 'MPV', condition: 'Bekas', status: 'Tersedia',
    price: 365000000, transmission: 'AT', fuel: 'Diesel',
    engine: '2.393 cc Diesel, 150 PS', seats: 7, km: 48000, color: 'Silver Metalik',
    image: 'assets/cars/toyota-innova.jpg', featured: true,
    features: ['Servis resmi Toyota', 'Pajak hidup', 'Tangan pertama', 'Kaptain seat', 'Kamera mundur'],
    description: 'Innova Reborn diesel istimewa, terawat, bebas banjir & tabrak. Garansi mesin 1 tahun.',
  },
  {
    id: 'veloz-2020',
    brand: 'Toyota', model: 'Avanza Veloz', variant: '1.5 AT',
    year: 2020, type: 'MPV', condition: 'Bekas', status: 'Tersedia',
    price: 185000000, transmission: 'AT', fuel: 'Bensin',
    engine: '1.496 cc, 104 PS', seats: 7, km: 52000, color: 'Putih',
    image: 'assets/cars/toyota-veloz.png', featured: true,
    features: ['Servis rutin', 'Pajak panjang', 'Ban baru', 'Head unit layar sentuh', 'Kunci serep lengkap'],
    description: 'Veloz matic irit dan bandel, kondisi siap pakai. Cocok untuk mobil pertama keluarga.',
  },
  {
    id: 'luxio-2022',
    brand: 'Daihatsu', model: 'Luxio', variant: '1.5 X MT',
    year: 2022, type: 'MPV', condition: 'Bekas', status: 'Tersedia',
    price: 185000000, transmission: 'MT', fuel: 'Bensin',
    engine: '1.495 cc, 97 PS', seats: 8, km: 40000, color: 'Abu-abu Metalik',
    image: 'assets/cars/daihatsu-luxio.jpg', featured: false,
    features: ['Kabin lega 8 penumpang', 'Double blower AC', 'Pintu geser', 'Bagasi luas', 'Pajak hidup'],
    description: 'MPV kabin luas andalan keluarga besar maupun usaha travel, perawatan mudah dan murah.',
  },
  {
    id: 'granmax-mb-2021',
    brand: 'Daihatsu', model: 'Gran Max', variant: 'MB 1.5 AC',
    year: 2021, type: 'Minibus', condition: 'Bekas', status: 'Tersedia',
    price: 155000000, transmission: 'MT', fuel: 'Bensin',
    engine: '1.495 cc, 97 PS', seats: 8, km: 68000, color: 'Putih',
    image: 'assets/cars/daihatsu-granmax.webp', featured: false,
    features: ['AC dingin', 'Pintu geser', 'Power steering', 'Mesin halus', 'Siap untuk usaha'],
    description: 'Minibus serbaguna untuk usaha, antar jemput, dan angkutan karyawan. Mesin sehat, kaki-kaki senyap.',
  },
];
